title: CriptoEduAr PREMIUM
description: "Domina el mercado crypto con análisis en tiempo real y herramientas profesionales."
theme: minima
baseurl: "" # Si tu sitio está en un subdirectorio, indícalo aquí
url: "https://ariasalejo.github.io/Cripto.Eduar"  # Tu URL de GitHub Pages
